### ISSUE TITLE
Question: Recipes missing instructions

### ISSUE THREAD

**Issue by Intecpsp** [tmack8001/picopak-library#1]
I got a couple Z kits (Pacific Brunch Stout Z Kit (HK) and Devil's Food Chocolate Porter Z Kit (HK)) and looked through your library to find that they are both blank. How could that be? Also, there are many for the devil's food and not all are the same.

https://github.com/tmack8001/picopak-library/search?q=devil%27s+food&unscoped_q=devil%27s+food
https://github.com/tmack8001/picopak-library/search?q=pacific+brunch&unscoped_q=pacific+brunch

Is there a way to get the device instructions for those?

**Comment by tmack8001** [comment]
I've never seen a zpak. So maybe I was missing the syntax of the interaction or example RID (recipeId).

@Intecpsp can you upload a picture of the pak label that would be used to retrieve the Pak instruction when entering on your Z?

**Comment by Intecpsp** [comment]
Here are both of them. ![IMG_20200730_072228.jpg](https://user-images.githubusercontent.com/1164012/88917434-bc271900-d235-11ea-989e-f33bf95974a0.jpg)
![IMG_20200730_072253.jpg](https://user-images.githubusercontent.com/1164012/88917443-bfbaa000-d235-11ea-9f72-24e18aa748be.jpg)

**Comment by Intecpsp** [comment]
Here are both of them

![IMG_20200730_072253.jpg](https://user-images.githubusercontent.com/1164012/88917538-ed9fe480-d235-11ea-959d-d4478d0f6e46.jpg)
![IMG_20200730_072228.jpg](https://user-images.githubusercontent.com/1164012/88917541-f0023e80-d235-11ea-83b7-af872c77f3ee.jpg)

**Comment by tmack8001** [comment]
I did notice there were 238 missing recipes (10000 - 10238) as I stopped the script at 9999 initially thinking they limited the amount of numbers selectable on the Z to 4, but later found you can enter a few more.

Though these two have an FID of 9935 and 9901 and thus should be these recipes:
- Devil's Food Chocolate Porter - https://github.com/tmack8001/picopak-library/blob/master/recipes/picopaks/9935.json
- Pacific Brunch Stout Z Kit - https://github.com/tmack8001/picopak-library/blob/218cc70872abe72cd826000b173ec566f9e9a012/recipes/picopaks/9901.json

The interesting thing here is that the "steps" are empty.

```
{"PicoRecipeID":9935,"PicoBeerID":756,"Name":"Devil's Food Chocolate Porter Z Kit (HK)","Abv":-1,"Ibu":-1,"Steps":[]}
```

Let me go plug that into my Z and see what is used to fetch the machine steps. I haven't pulled all these into the offline server yet, but will look at doing that today @Intecpsp similar to how we have import setup for Pico C/S/Pro units I'll do a similar import for picobrew.com recipes for the Z (since they are different). In the case that the mothership goes down the back up plan would be to import from this library of picopak recipes.

**Comment by Intecpsp** [comment]
I suspected it was those, but wanted to confirm. Thank you for your help! Why were there so many Devil's Food recipes for non-Z?

**Comment by tmack8001** [comment]
Ok so after additionally debugging I found all these recipes are simply the picopak and freestyle paks.

The Z recipe IDs that are entered into the machine of the ZPaks you sent are actually 140930 and 141305... but on the Z there is a "search" and "view all" functions for ZPaks (previously I never mapped those requests).

Doing this there is only 27 ZPak kits available. I'm going to export those here as well so those capabilities can be mapped as well into the offline server.

**Comment by tmack8001** [comment]
@Intecpsp here are the recipe instructions for those zpaks

Pacific Brunch Stout - https://github.com/tmack8001/picopak-library/blob/master/recipes/zpaks/140930.json
Devil's Food Z Kit - https://github.com/tmack8001/picopak-library/blob/master/recipes/zpaks/141305.json

I've also updated the export script to have logic for pulling out all of the ZPaks and found there to be 37 paks defined which sounds about right.

I've wanted to build these capabilities into the offline server so you can still just "select" an rid or zrid and get the recipe needed for the pack, just haven't gotten around to that yet.

**Comment by Intecpsp** [comment]
Awesome, thank you so much!

**Comment by tmack8001** [comment]
@Intecpsp no problem at all. If you see anything else strange let me know. To use any of these with the offline server the JSON payload needs to be modified slightly  into the format expected by the offline cheifwigms server (or other picobrew replicating project).
